trigger:
  batch: true
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

jobs:
  - job: build
    displayName: 'Build'
    pool:
      vmImage: 'windows-latest'
    steps:
      - checkout: self
        clean: true
        submodules: true
        persistCredentials: true

      - task: CmdLine@2
        displayName: "Clone Server Branch"
        condition: contains(variables['Build.SourceBranch'], 'refs')
        inputs:
          script: "git clone --single-branch --branch $(Build.SourceBranchName) --depth=1 https://github.com/jellyfin/jellyfin.git $(Build.SourcesDirectory)/jellyfin"

      - task: CmdLine@2
        displayName: "Clone Server Target"
        condition: in(variables['Build.Reason'], 'PullRequest')
        inputs:
          script: "git clone --single-branch --branch $(System.PullRequest.TargetBranch) --depth=1 https://github.com/jellyfin/jellyfin.git $(Build.SourcesDirectory)/jellyfin"

      - task: CmdLine@2
        displayName: "Clone Web Branch"
        condition: contains(variables['Build.SourceBranch'], 'refs')
        inputs:
          script: "git clone --single-branch --branch $(Build.SourceBranchName) --depth=1 https://github.com/jellyfin/jellyfin-web.git $(Agent.TempDirectory)/jellyfin-web"

      - task: CmdLine@2
        displayName: "Clone Web Target"
        condition: in(variables['Build.Reason'], 'PullRequest')
        inputs:
          script: "git clone --single-branch --branch $(System.PullRequest.TargetBranch) --depth 1 https://github.com/jellyfin/jellyfin-web.git $(Agent.TempDirectory)/jellyfin-web"

      - task: NodeTool@0
        displayName: "Install Node"
        inputs:
          versionSpec: "12.x"

      - task: CmdLine@2
        displayName: "Build Web Client"
        inputs:
          script: yarn install
          workingDirectory: $(Agent.TempDirectory)/jellyfin-web

      - task: CopyFiles@2
        displayName: "Copy Web Client"
        inputs:
          sourceFolder: $(Agent.TempDirectory)/jellyfin-web/dist
          contents: "**"
          targetFolder: $(Build.SourcesDirectory)/jellyfin/jellyfin-web
          cleanTargetFolder: true
          overWrite: true
          flattenFolders: false

      - task: CmdLine@2
        displayName: "Clone UX Repository"
        inputs:
          script: 'git clone --depth=1 https://github.com/jellyfin/jellyfin-ux $(Agent.TempDirectory)/jellyfin-ux'

      - task: PowerShell@2
        displayName: "Build NSIS Installer"
        inputs:
          targetType: "filePath"
          filePath: build-jellyfin.ps1
          arguments: -InstallFFMPEG -InstallNSSM -MakeNSIS -InstallTrayApp -UXLocation $(Agent.TempDirectory)\jellyfin-ux -InstallLocation $(Build.ArtifactStagingDirectory)
          errorActionPreference: "stop"
          workingDirectory: $(Build.SourcesDirectory)/jellyfin

      - task: CopyFiles@2
        displayName: "Copy NSIS Installer"
        inputs:
          sourceFolder: $(Build.SourcesDirectory)/nsis
          contents: "jellyfin*.exe"
          targetFolder: $(System.ArtifactsDirectory)/setup
          cleanTargetFolder: true
          overWrite: true
          flattenFolders: true

      - task: PublishPipelineArtifact@0
        displayName: "Publish Artifact"
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)/setup"
          artifactName: "jellyfin-server-windows"
